struct _LDR_DATA_TABLE_ENTRY {
	struct _LIST_ENTRY	InLoadOrderLinks;
	struct _LIST_ENTRY	InMemoryOrderLinks;
	struct _LIST_ENTRY	InInitializationOrderLinks;
	void	*DllBase;
	void	*EntryPoint;
	uint32_t	SizeOfImage;
	struct _UNICODE_STRING	FullDllName;
	struct _UNICODE_STRING	BaseDllName;
	union {
		uint8_t	FlagGroup[4];
		uint32_t	Flags;
		struct Bitstruct 1struct 0,struct Pos	PackagedBinary;
		struct Bitstruct 1struct 1,struct Pos	MarkedForRemoval;
		struct Bitstruct 1struct 2,struct Pos	ImageDll;
		struct Bitstruct 1struct 3,struct Pos	LoadNotificationsSent;
		struct Bitstruct 1struct 4,struct Pos	TelemetryEntryProcessed;
		struct Bitstruct 1struct 5,struct Pos	ProcessStaticImport;
		struct Bitstruct 1struct 6,struct Pos	InLegacyLists;
		struct Bitstruct 1struct 7,struct Pos	InIndexes;
		struct Bitstruct 1struct 8,struct Pos	ShimDll;
		struct Bitstruct 1struct 9,struct Pos	InExceptionTable;
		struct Bitsstruct 2struct 10,struct Pos	ReservedFlags1;
		struct Bitstruct 1struct 12,struct Pos	LoadInProgress;
		struct Bitstruct 1struct 13,struct Pos	LoadConfigProcessed;
		struct Bitstruct 1struct 14,struct Pos	EntryProcessed;
		struct Bitstruct 1struct 15,struct Pos	ProtectDelayLoad;
		struct Bitsstruct 2struct 16,struct Pos	ReservedFlags3;
		struct Bitstruct 1struct 18,struct Pos	DontCallForThreads;
		struct Bitstruct 1struct 19,struct Pos	ProcessAttachCalled;
		struct Bitstruct 1struct 20,struct Pos	ProcessAttachFailed;
		struct Bitstruct 1struct 21,struct Pos	CorDeferredValidate;
		struct Bitstruct 1struct 22,struct Pos	CorImage;
		struct Bitstruct 1struct 23,struct Pos	DontRelocate;
		struct Bitstruct 1struct 24,struct Pos	CorILOnly;
		struct Bitsstruct 3struct 25,struct Pos	ReservedFlags5;
		struct Bitstruct 1struct 28,struct Pos	Redirected;
		struct Bitsstruct 2struct 29,struct Pos	ReservedFlags6;
		struct Bitstruct 1struct 31,struct Pos	CompatDatabaseProcessed;
	};
	uint16_t	ObsoleteLoadCount;
	uint16_t	TlsIndex;
	struct _LIST_ENTRY	HashLinks;
	uint32_t	TimeDateStamp;
	struct _ACTIVATION_CONTEXT	*EntryPointActivationContext;
	void	*Lock;
	struct _LDR_DDAG_NODE	*DdagNode;
	struct _LIST_ENTRY	NodeModuleLink;
	struct _LDRP_LOAD_CONTEXT	*LoadContext;
	void	*ParentDllBase;
	void	*SwitchBackContext;
	struct _RTL_BALANCED_NODE	BaseAddressIndexNode;
	struct _RTL_BALANCED_NODE	MappingInfoIndexNode;
	uint64_t	OriginalBase;
	struct _LARGE_INTEGER	LoadTime;
	uint32_t	BaseNameHashValue;
	struct _LDR_DLL_LOAD_REASON	LoadReason;
	uint32_t	ImplicitPathOptions;
	uint32_t	ReferenceCount;
	uint32_t	DependentLoadFlags;
}__attribute__((packed));
