struct _PEB {
	unsigned char	InheritedAddressSpace;
	unsigned char	ReadImageFileExecOptions;
	unsigned char	BeingDebugged;
	unsigned char	BitField;
	unsigned char	Padding0[4];
	void	*	Mutant;
	void	*	ImageBaseAddress;
	struct _PEB_LDR_DATA	*	Ldr;
	struct _RTL_USER_PROCESS_PARAMETERS	*	ProcessParameters;
	void	*	SubSystemData;
	void	*	ProcessHeap;
	struct _RTL_CRITICAL_SECTION	*	FastPebLock;
	struct _SLIST_HEADER	*	AtlThunkSListPtr;
	void	*	IFEOKey;
	uint32_t	CrossProcessFlags;
	unsigned char	Padding1[4];
	void	*	KernelCallbackTable;
	void	*	UserSharedInfoPtr;
	uint32_t	SystemReserved[1];
	uint32_t	AtlThunkSListPtr32;
	void	*	ApiSetMap;
	uint32_t	TlsExpansionCounter;
	unsigned char	Padding2[4];
	void	*	TlsBitmap;
	uint32_t	TlsBitmapBits[2];
	void	*	ReadOnlySharedMemoryBase;
	void	*	SparePvoid0;
	void	*	*	ReadOnlyStaticServerData;
	void	*	AnsiCodePageData;
	void	*	OemCodePageData;
	void	*	UnicodeCaseTableData;
	uint32_t	NumberOfProcessors;
	uint32_t	NtGlobalFlag;
	struct _LARGE_INTEGER	CriticalSectionTimeout;
	uint64_t	HeapSegmentReserve;
	uint64_t	HeapSegmentCommit;
	uint64_t	HeapDeCommitTotalFreeThreshold;
	uint64_t	HeapDeCommitFreeBlockThreshold;
	uint32_t	NumberOfHeaps;
	uint32_t	MaximumNumberOfHeaps;
	void	*	*	ProcessHeaps;
	void	*	GdiSharedHandleTable;
	void	*	ProcessStarterHelper;
	uint32_t	GdiDCAttributeList;
	unsigned char	Padding3[4];
	struct _RTL_CRITICAL_SECTION	*	LoaderLock;
	uint32_t	OSMajorVersion;
	uint32_t	OSMinorVersion;
	uint16_t	OSBuildNumber;
	uint16_t	OSCSDVersion;
	uint32_t	OSPlatformId;
	uint32_t	ImageSubsystem;
	uint32_t	ImageSubsystemMajorVersion;
	uint32_t	ImageSubsystemMinorVersion;
	unsigned char	Padding4[4];
	uint64_t	ActiveProcessAffinityMask;
	uint32_t	GdiHandleBuffer[60];
	struct void	*	PostProcessInitRoutine;
	void	*	TlsExpansionBitmap;
	uint32_t	TlsExpansionBitmapBits[32];
	uint32_t	SessionId;
	unsigned char	Padding5[4];
	struct _ULARGE_INTEGER	AppCompatFlags;
	struct _ULARGE_INTEGER	AppCompatFlagsUser;
	void	*	pShimData;
	void	*	AppCompatInfo;
	struct _UNICODE_STRING	CSDVersion;
	struct _ACTIVATION_CONTEXT_DATA	*	ActivationContextData;
	struct _ASSEMBLY_STORAGE_MAP	*	ProcessAssemblyStorageMap;
	struct _ACTIVATION_CONTEXT_DATA	*	SystemDefaultActivationContextData;
	struct _ASSEMBLY_STORAGE_MAP	*	SystemAssemblyStorageMap;
	uint64_t	MinimumStackCommit;
	struct _FLS_CALLBACK_INFO	*	FlsCallback;
	struct _LIST_ENTRY	FlsListHead;
	void	*	FlsBitmap;
	uint32_t	FlsBitmapBits[4];
	uint32_t	FlsHighIndex;
	void	*	WerRegistrationData;
	void	*	WerShipAssertPtr;
	void	*	pUnused;
	void	*	pImageHeaderHash;
	uint32_t	TracingFlags;
	unsigned char	Padding6[4];
	uint64_t	CsrServerReadOnlySharedMemoryBase;
	uint64_t	TppWorkerpListLock;
	struct _LIST_ENTRY	TppWorkerpList;
	void	*	WaitOnAddressHashTable[128];
}__attribute__((packed));

