
struct _EJOB {
	struct _KEVENT	Event;
	struct _LIST_ENTRY	JobLinks;
	struct _LIST_ENTRY	ProcessListHead;
	struct _ERESOURCE	JobLock;
	struct _LARGE_INTEGER	TotalUserTime;
	struct _LARGE_INTEGER	TotalKernelTime;
	struct _LARGE_INTEGER	ThisPeriodTotalUserTime;
	struct _LARGE_INTEGER	ThisPeriodTotalKernelTime;
	uint32_t	TotalPageFaultCount;
	uint32_t	TotalProcesses;
	uint32_t	ActiveProcesses;
	uint32_t	TotalTerminatedProcesses;
	struct _LARGE_INTEGER	PerProcessUserTimeLimit;
	struct _LARGE_INTEGER	PerJobUserTimeLimit;
	uint32_t	MinimumWorkingSetSize;
	uint32_t	MaximumWorkingSetSize;
	uint32_t	LimitFlags;
	uint32_t	ActiveProcessLimit;
	struct _KAFFINITY_EX	Affinity;
	uint8_t	PriorityClass;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	struct _JOB_ACCESS_STATE	*AccessState;
	uint32_t	UIRestrictionsClass;
	uint32_t	EndOfJobTimeAction;
	void	*CompletionPort;
	void	*CompletionKey;
	uint32_t	SessionId;
	uint32_t	SchedulingClass;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	uint64_t	ReadOperationCount;
	uint64_t	WriteOperationCount;
	uint64_t	OtherOperationCount;
	uint64_t	ReadTransferCount;
	uint64_t	WriteTransferCount;
	uint64_t	OtherTransferCount;
	uint32_t	ProcessMemoryLimit;
	uint32_t	JobMemoryLimit;
	uint32_t	PeakProcessMemoryUsed;
	uint32_t	PeakJobMemoryUsed;
	uint64_t	CurrentJobMemoryUsed;
	struct _EX_PUSH_LOCK	MemoryLimitsLock;
	struct _LIST_ENTRY	JobSetLinks;
	uint32_t	MemberLevel;
	uint32_t	JobFlags;
}__attribute__((packed));
