
struct _FILE_OBJECT {
	int16_t	Type;
	int16_t	Size;
	struct _DEVICE_OBJECTstruct Ptr32	DeviceObject;
	struct _VPBstruct Ptr32	Vpb;
	voidstruct Ptr32	FsContext;
	voidstruct Ptr32	FsContext2;
	struct _SECTION_OBJECT_POINTERSstruct Ptr32	SectionObjectPointer;
	voidstruct Ptr32	PrivateCacheMap;
	int32_t	FinalStatus;
	struct _FILE_OBJECTstruct Ptr32	RelatedFileObject;
	uint8_t	LockOperation;
	uint8_t	DeletePending;
	uint8_t	ReadAccess;
	uint8_t	WriteAccess;
	uint8_t	DeleteAccess;
	uint8_t	SharedRead;
	uint8_t	SharedWrite;
	uint8_t	SharedDelete;
	uint32_t	Flags;
	struct _UNICODE_STRING	FileName;
	struct _LARGE_INTEGER	CurrentByteOffset;
	uint32_t	Waiters;
	uint32_t	Busy;
	voidstruct Ptr32	LastLock;
	struct _KEVENT	Lock;
	struct _KEVENT	Event;
	struct _IO_COMPLETION_CONTEXTstruct Ptr32	CompletionContext;
	uint32_t	IrpListLock;
	struct _LIST_ENTRY	IrpList;
	voidstruct Ptr32	FileObjectExtension;
}__attribute__((packed));
