
/* BpbState */
#define	BpbCpuIdle	0x00000001
#define	BpbFlushRsbOnTrap	0x00000002
#define	BpbIbpbOnReturn	0x00000004
#define	BpbIbpbOnTrap	0x00000008
#define	BpbReserved	0x000000F0

/* BpbFeatures */
#define	BpbClearOnIdle	0x00000001
#define	BpbEnabled	0x00000002
#define	BpbSmep	0x00000004
#define	BpbFeaturesReserved	0x000000F8

/* NormalDpcState */
#define	DpcThreadActive	0x00000001

struct _KPRCB {
	uint16_t	MinorVersion;
	uint16_t	MajorVersion;
	struct _KTHREAD	*CurrentThread;
	struct _KTHREAD	*NextThread;
	struct _KTHREAD	*IdleThread;
	uint8_t	LegacyNumber;
	uint8_t	NestingLevel;
	uint16_t	BuildType;
	struct Char	CpuType;
	struct Char	CpuID;
	union {
		uint16_t	CpuStep;
		uint8_t	CpuStepping;
	};
	uint8_t	CpuModel;
	struct _KPROCESSOR_STATE	ProcessorState;
	uint32_t	KernelReserved[16];
	uint32_t	HalReserved[16];
	uint32_t	CFlushSize;
	uint8_t	CoresPerPhysicalProcessor;
	uint8_t	LogicalProcessorsPerCore;
	uint8_t	PrcbPad0[2];
	uint32_t	MHz;
	uint8_t	CpuVendor;
	uint8_t	GroupIndex;
	uint16_t	Group;
	uint32_t	GroupSetMember;
	uint32_t	Number;
	uint8_t	PrcbPad1[72];
	struct _KSPIN_LOCK_QUEUE	LockQueue[17];
	struct _KTHREAD	*NpxThread;
	uint32_t	InterruptCount;
	uint32_t	KernelTime;
	uint32_t	UserTime;
	uint32_t	DpcTime;
	uint32_t	DpcTimeCount;
	uint32_t	InterruptTime;
	uint32_t	AdjustDpcThreshold;
	uint32_t	PageColor;
	uint8_t	DebuggerSavedIRQL;
	uint8_t	NodeColor;
	uint8_t	PrcbPad20[2];
	uint32_t	NodeShiftedColor;
	struct _KNODE	*ParentNode;
	uint32_t	SecondaryColorMask;
	uint32_t	DpcTimeLimit;
	uint32_t	PrcbPad21[2];
	uint32_t	CcFastReadNoWait;
	uint32_t	CcFastReadWait;
	uint32_t	CcFastReadNotPossible;
	uint32_t	CcCopyReadNoWait;
	uint32_t	CcCopyReadWait;
	uint32_t	CcCopyReadNoWaitMiss;
	int32_t	MmSpinLockOrdering;
	int32_t	IoReadOperationCount;
	int32_t	IoWriteOperationCount;
	int32_t	IoOtherOperationCount;
	struct _LARGE_INTEGER	IoReadTransferCount;
	struct _LARGE_INTEGER	IoWriteTransferCount;
	struct _LARGE_INTEGER	IoOtherTransferCount;
	uint32_t	CcFastMdlReadNoWait;
	uint32_t	CcFastMdlReadWait;
	uint32_t	CcFastMdlReadNotPossible;
	uint32_t	CcMapDataNoWait;
	uint32_t	CcMapDataWait;
	uint32_t	CcPinMappedDataCount;
	uint32_t	CcPinReadNoWait;
	uint32_t	CcPinReadWait;
	uint32_t	CcMdlReadNoWait;
	uint32_t	CcMdlReadWait;
	uint32_t	CcLazyWriteHotSpots;
	uint32_t	CcLazyWriteIos;
	uint32_t	CcLazyWritePages;
	uint32_t	CcDataFlushes;
	uint32_t	CcDataPages;
	uint32_t	CcLostDelayedWrites;
	uint32_t	CcFastReadResourceMiss;
	uint32_t	CcCopyReadWaitMiss;
	uint32_t	CcFastMdlReadResourceMiss;
	uint32_t	CcMapDataNoWaitMiss;
	uint32_t	CcMapDataWaitMiss;
	uint32_t	CcPinReadNoWaitMiss;
	uint32_t	CcPinReadWaitMiss;
	uint32_t	CcMdlReadNoWaitMiss;
	uint32_t	CcMdlReadWaitMiss;
	uint32_t	CcReadAheadIos;
	uint32_t	KeAlignmentFixupCount;
	uint32_t	KeExceptionDispatchCount;
	uint32_t	KeSystemCalls;
	uint32_t	AvailableTime;
	uint32_t	PrcbPad22[2];
	struct _PP_LOOKASIDE_LIST	PPLookasideList[16];
	struct _GENERAL_LOOKASIDE_POOL	PPNPagedLookasideList[32];
	struct _GENERAL_LOOKASIDE_POOL	PPPagedLookasideList[32];
	uint32_t	PacketBarrier;
	int32_t	ReverseStall;
	void	*IpiFrame;
	uint8_t	PrcbPad3[52];
	void	*CurrentPacket[3];
	uint32_t	TargetSet;
	void	*WorkerRoutine;
	uint32_t	IpiFrozen;
	uint8_t	PrcbPad4[40];
	uint32_t	RequestSummary;
	struct _KPRCB	*SignalDone;
	uint64_t	TrappedSecurityDomain;
	uint8_t	BpbState;
	uint8_t	BpbFeatures;
	uint8_t	BpbCurrentSpecCtrl;
	uint8_t	BpbKernelSpecCtrl;
	uint8_t	BpbNmiSpecCtrl;
	uint8_t	BpbUserSpecCtrl;
	uint8_t	PrcbPad50[42];
	struct _KDPC_DATA	DpcData[2];
	void	*DpcStack;
	int32_t	MaximumDpcQueueDepth;
	uint32_t	DpcRequestRate;
	uint32_t	MinimumDpcRate;
	uint32_t	DpcLastCount;
	uint32_t	PrcbLock;
	struct _KGATE	DpcGate;
	uint8_t	ThreadDpcEnable;
	uint8_t	QuantumEnd;
	uint8_t	DpcRoutineActive;
	uint8_t	IdleSchedule;
	union {
		int32_t	DpcRequestSummary;
		int16_t	DpcRequestSlot[2];
		int16_t	NormalDpcState;
	};
	int16_t	ThreadDpcState;
	uint32_t	TimerHand;
	uint32_t	LastTick;
	int32_t	MasterOffset;
	uint32_t	PrcbPad41[2];
	uint32_t	PeriodicCount;
	uint32_t	PeriodicBias;
	uint64_t	TickOffset;
	struct _KTIMER_TABLE	TimerTable;
	struct _KDPC	CallDpc;
	int32_t	ClockKeepAlive;
	uint8_t	ClockCheckSlot;
	uint8_t	ClockPollCycle;
	uint8_t	PrcbPad6[2];
	int32_t	DpcWatchdogPeriod;
	int32_t	DpcWatchdogCount;
	int32_t	ThreadWatchdogPeriod;
	int32_t	ThreadWatchdogCount;
	int32_t	KeSpinLockOrdering;
	uint32_t	PrcbPad70[1];
	struct _LIST_ENTRY	WaitListHead;
	uint32_t	WaitLock;
	uint32_t	ReadySummary;
	uint32_t	QueueIndex;
	struct _SINGLE_LIST_ENTRY	DeferredReadyListHead;
	uint64_t	StartCycles;
	uint64_t	CycleTime;
	uint32_t	HighCycleTime;
	uint32_t	PrcbPad71;
	uint64_t	PrcbPad72[2];
	struct _LIST_ENTRY	DispatcherReadyListHead[32];
	void	*ChainedInterruptList;
	int32_t	LookasideIrpFloat;
	int32_t	MmPageFaultCount;
	int32_t	MmCopyOnWriteCount;
	int32_t	MmTransitionCount;
	int32_t	MmCacheTransitionCount;
	int32_t	MmDemandZeroCount;
	int32_t	MmPageReadCount;
	int32_t	MmPageReadIoCount;
	int32_t	MmCacheReadCount;
	int32_t	MmCacheIoCount;
	int32_t	MmDirtyPagesWriteCount;
	int32_t	MmDirtyWriteIoCount;
	int32_t	MmMappedPagesWriteCount;
	int32_t	MmMappedWriteIoCount;
	uint32_t	CachedCommit;
	uint32_t	CachedResidentAvailable;
	void	*HyperPte;
	uint8_t	PrcbPad8[4];
	uint8_t	VendorString[13];
	uint8_t	InitialApicId;
	uint8_t	LogicalProcessorsPerPhysicalProcessor;
	uint8_t	PrcbPad9[5];
	uint32_t	FeatureBits;
	struct _LARGE_INTEGER	UpdateSignature;
	uint64_t	IsrTime;
	uint64_t	RuntimeAccumulation;
	struct _PROCESSOR_POWER_STATE	PowerState;
	struct _KDPC	DpcWatchdogDpc;
	struct _KTIMER	DpcWatchdogTimer;
	void	*WheaInfo;
	void	*EtwSupport;
	struct _SLIST_HEADER	InterruptObjectPool;
	struct _SLIST_HEADER	HypercallPageList;
	void	*HypercallPageVirtual;
	void	*VirtualApicAssist;
	uint64_t	*StatisticsPage;
	void	*RateControl;
	struct _CACHE_DESCRIPTOR	Cache[5];
	uint32_t	CacheCount;
	uint32_t	CacheProcessorMask[5];
	struct _KAFFINITY_EX	PackageProcessorSet;
	uint32_t	PrcbPad91[1];
	uint32_t	CoreProcessorSet;
	struct _KDPC	TimerExpirationDpc;
	uint32_t	SpinLockAcquireCount;
	uint32_t	SpinLockContentionCount;
	uint32_t	SpinLockSpinCount;
	uint32_t	IpiSendRequestBroadcastCount;
	uint32_t	IpiSendRequestRoutineCount;
	uint32_t	IpiSendSoftwareInterruptCount;
	uint32_t	ExInitializeResourceCount;
	uint32_t	ExReInitializeResourceCount;
	uint32_t	ExDeleteResourceCount;
	uint32_t	ExecutiveResourceAcquiresCount;
	uint32_t	ExecutiveResourceContentionsCount;
	uint32_t	ExecutiveResourceReleaseExclusiveCount;
	uint32_t	ExecutiveResourceReleaseSharedCount;
	uint32_t	ExecutiveResourceConvertsCount;
	uint32_t	ExAcqResExclusiveAttempts;
	uint32_t	ExAcqResExclusiveAcquiresExclusive;
	uint32_t	ExAcqResExclusiveAcquiresExclusiveRecursive;
	uint32_t	ExAcqResExclusiveWaits;
	uint32_t	ExAcqResExclusiveNotAcquires;
	uint32_t	ExAcqResSharedAttempts;
	uint32_t	ExAcqResSharedAcquiresExclusive;
	uint32_t	ExAcqResSharedAcquiresShared;
	uint32_t	ExAcqResSharedAcquiresSharedRecursive;
	uint32_t	ExAcqResSharedWaits;
	uint32_t	ExAcqResSharedNotAcquires;
	uint32_t	ExAcqResSharedStarveExclusiveAttempts;
	uint32_t	ExAcqResSharedStarveExclusiveAcquiresExclusive;
	uint32_t	ExAcqResSharedStarveExclusiveAcquiresShared;
	uint32_t	ExAcqResSharedStarveExclusiveAcquiresSharedRecursive;
	uint32_t	ExAcqResSharedStarveExclusiveWaits;
	uint32_t	ExAcqResSharedStarveExclusiveNotAcquires;
	uint32_t	ExAcqResSharedWaitForExclusiveAttempts;
	uint32_t	ExAcqResSharedWaitForExclusiveAcquiresExclusive;
	uint32_t	ExAcqResSharedWaitForExclusiveAcquiresShared;
	uint32_t	ExAcqResSharedWaitForExclusiveAcquiresSharedRecursive;
	uint32_t	ExAcqResSharedWaitForExclusiveWaits;
	uint32_t	ExAcqResSharedWaitForExclusiveNotAcquires;
	uint32_t	ExSetResOwnerPointerExclusive;
	uint32_t	ExSetResOwnerPointerSharedNew;
	uint32_t	ExSetResOwnerPointerSharedOld;
	uint32_t	ExTryToAcqExclusiveAttempts;
	uint32_t	ExTryToAcqExclusiveAcquires;
	uint32_t	ExBoostExclusiveOwner;
	uint32_t	ExBoostSharedOwners;
	uint32_t	ExEtwSynchTrackingNotificationsCount;
	uint32_t	ExEtwSynchTrackingNotificationsAccountedCount;
	struct _CONTEXT	*Context;
	uint32_t	ContextFlags;
	struct _XSAVE_AREA	*ExtendedState;
	struct _KINTERRUPT	*VectorToInterruptObject[208];
	uint32_t	PrcbPad100[15];
	uint32_t	ProcessorSignature;
	uint32_t	PrcbShadowMappedPagePad1[335];
	uint32_t	KernelDirectoryTableBase;
	uint32_t	EspBaseShadow;
	uint32_t	UserEspShadow;
	uint32_t	ShadowFlags;
	uint32_t	UserDS;
	uint32_t	UserES;
	uint32_t	UserFS;
	void	*EspIretd;
	uint32_t	RestoreSegOption;
	uint32_t	SavedEsi;
	uint32_t	DbgLogs[512];
	uint32_t	DbgCount;
	uint32_t	PrcbShadowMappedPagePad2[501];
}__attribute__((packed));
