
struct _MMSUPPORT {
	struct _EX_PUSH_LOCK	WorkingSetMutex;
	struct _KGATE	*ExitGate;
	void	*AccessLog;
	struct _LIST_ENTRY	WorkingSetExpansionLinks;
	uint32_t	AgeDistribution[7];
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	uint8_t	__padding4__;
	uint8_t	__padding5__;
	uint8_t	__padding6__;
	uint8_t	__padding7__;
	uint8_t	__padding8__;
	uint8_t	__padding9__;
	uint8_t	__padding10__;
	uint8_t	__padding11__;
	uint8_t	__padding12__;
	uint8_t	__padding13__;
	uint8_t	__padding14__;
	uint8_t	__padding15__;
	uint8_t	__padding16__;
	uint8_t	__padding17__;
	uint8_t	__padding18__;
	uint8_t	__padding19__;
	uint8_t	__padding20__;
	uint8_t	__padding21__;
	uint8_t	__padding22__;
	uint8_t	__padding23__;
	uint32_t	MinimumWorkingSetSize;
	uint32_t	WorkingSetSize;
	uint32_t	WorkingSetPrivateSize;
	uint32_t	MaximumWorkingSetSize;
	uint32_t	ChargedWslePages;
	uint32_t	ActualWslePages;
	uint32_t	WorkingSetSizeOverhead;
	uint32_t	PeakWorkingSetSize;
	uint32_t	HardFaultCount;
	struct _MMWSL	*VmWorkingSetList;
	uint16_t	NextPageColor;
	uint16_t	LastTrimStamp;
	uint32_t	PageFaultCount;
	uint32_t	RepurposeCount;
	void	*ShadowMapping;
	struct _MMSUPPORT_FLAGS	Flags;
}__attribute__((packed));
