
struct _DEVOBJ_EXTENSION {
	int16_t	Type;
	uint16_t	Size;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	struct _DEVICE_OBJECT	*DeviceObject;
	uint32_t	PowerFlags;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	struct _DEVICE_OBJECT_POWER_EXTENSION	*Dope;
	uint32_t	ExtensionFlags;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	void	*DeviceNode;
	struct _DEVICE_OBJECT	*AttachedTo;
	int32_t	StartIoCount;
	int32_t	StartIoKey;
	uint32_t	StartIoFlags;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	struct _VPB	*Vpb;
	void	*DependencyNode;
	void	*InterruptContext;
	void	*VerifierContext;
}__attribute__((packed));
