
struct _DEVICE_OBJECT {
	int16_t	Type;
	uint16_t	Size;
	int32_t	ReferenceCount;
	struct _DRIVER_OBJECT	*DriverObject;
	struct _DEVICE_OBJECT	*NextDevice;
	struct _DEVICE_OBJECT	*AttachedDevice;
	struct _IRP	*CurrentIrp;
	struct _IO_TIMER	*Timer;
	uint32_t	Flags;
	uint32_t	Characteristics;
	struct _VPB	*Vpb;
	void	*DeviceExtension;
	uint32_t	DeviceType;
	struct Char	StackSize;
	struct <unnamed-tag>	Queue;
	uint32_t	AlignmentRequirement;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	struct _KDEVICE_QUEUE	DeviceQueue;
	struct _KDPC	Dpc;
	uint32_t	ActiveThreadCount;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	void	*SecurityDescriptor;
	struct _KEVENT	DeviceLock;
	uint16_t	SectorSize;
	uint16_t	Spare1;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	struct _DEVOBJ_EXTENSION	*DeviceObjectExtension;
	void	*Reserved;
}__attribute__((packed));
