
struct _FAST_IO_DISPATCH {
	uint32_t	SizeOfFastIoDispatch;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	struct charstruct unsigned	*FastIoCheckIfPossible;
	struct charstruct unsigned	*FastIoRead;
	struct charstruct unsigned	*FastIoWrite;
	struct charstruct unsigned	*FastIoQueryBasicInfo;
	struct charstruct unsigned	*FastIoQueryStandardInfo;
	struct charstruct unsigned	*FastIoLock;
	struct charstruct unsigned	*FastIoUnlockSingle;
	struct charstruct unsigned	*FastIoUnlockAll;
	struct charstruct unsigned	*FastIoUnlockAllByKey;
	struct charstruct unsigned	*FastIoDeviceControl;
	void	*AcquireFileForNtCreateSection;
	void	*ReleaseFileForNtCreateSection;
	void	*FastIoDetachDevice;
	struct charstruct unsigned	*FastIoQueryNetworkOpenInfo;
	struct long	*AcquireForModWrite;
	struct charstruct unsigned	*MdlRead;
	struct charstruct unsigned	*MdlReadComplete;
	struct charstruct unsigned	*PrepareMdlWrite;
	struct charstruct unsigned	*MdlWriteComplete;
	struct charstruct unsigned	*FastIoReadCompressed;
	struct charstruct unsigned	*FastIoWriteCompressed;
	struct charstruct unsigned	*MdlReadCompleteCompressed;
	struct charstruct unsigned	*MdlWriteCompleteCompressed;
	struct charstruct unsigned	*FastIoQueryOpen;
	struct long	*ReleaseForModWrite;
	struct long	*AcquireForCcFlush;
	struct long	*ReleaseForCcFlush;
}__attribute__((packed));
