
struct _HEAP_LFH_CONTEXT {
	void	*BackendCtx;
	struct _HEAP_SUBALLOCATOR_CALLBACKS	Callbacks;
	struct _RTL_SRWLOCK	SubsegmentCreationLock;
	uint8_t	MaxAffinity;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	uint8_t	__padding4__;
	uint8_t	__padding5__;
	uint8_t	__padding6__;
	uint8_t	*AffinityModArray;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	uint8_t	__padding4__;
	uint8_t	__padding5__;
	uint8_t	__padding6__;
	uint8_t	__padding7__;
	uint8_t	__padding8__;
	uint8_t	__padding9__;
	uint8_t	__padding10__;
	uint8_t	__padding11__;
	uint8_t	__padding12__;
	uint8_t	__padding13__;
	uint8_t	__padding14__;
	struct _HEAP_LFH_SUBSEGMENT_CACHE	SubsegmentCache;
	struct _HEAP_LFH_BUCKET	*Buckets[129];
}__attribute__((packed));
