
struct _MMSUPPORT_INSTANCE {
	uint16_t	NextPageColor;
	uint16_t	LastTrimStamp;
	uint32_t	PageFaultCount;
	uint64_t	TrimmedPageCount;
	struct _MMWSL_INSTANCE	*VmWorkingSetList;
	struct _LIST_ENTRY	WorkingSetExpansionLinks;
	uint64_t	AgeDistribution[7];
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	uint8_t	__padding4__;
	uint8_t	__padding5__;
	uint8_t	__padding6__;
	uint8_t	__padding7__;
	uint8_t	__padding8__;
	uint8_t	__padding9__;
	uint8_t	__padding10__;
	uint8_t	__padding11__;
	uint8_t	__padding12__;
	uint8_t	__padding13__;
	uint8_t	__padding14__;
	uint8_t	__padding15__;
	uint8_t	__padding16__;
	uint8_t	__padding17__;
	uint8_t	__padding18__;
	uint8_t	__padding19__;
	uint8_t	__padding20__;
	uint8_t	__padding21__;
	uint8_t	__padding22__;
	uint8_t	__padding23__;
	uint8_t	__padding24__;
	uint8_t	__padding25__;
	uint8_t	__padding26__;
	uint8_t	__padding27__;
	uint8_t	__padding28__;
	uint8_t	__padding29__;
	uint8_t	__padding30__;
	uint8_t	__padding31__;
	uint8_t	__padding32__;
	uint8_t	__padding33__;
	uint8_t	__padding34__;
	uint8_t	__padding35__;
	uint8_t	__padding36__;
	uint8_t	__padding37__;
	uint8_t	__padding38__;
	uint8_t	__padding39__;
	uint8_t	__padding40__;
	uint8_t	__padding41__;
	uint8_t	__padding42__;
	uint8_t	__padding43__;
	uint8_t	__padding44__;
	uint8_t	__padding45__;
	uint8_t	__padding46__;
	uint8_t	__padding47__;
	struct _KGATE	*ExitOutswapGate;
	uint64_t	MinimumWorkingSetSize;
	uint64_t	WorkingSetLeafSize;
	uint64_t	WorkingSetLeafPrivateSize;
	uint64_t	WorkingSetSize;
	uint64_t	WorkingSetPrivateSize;
	uint64_t	MaximumWorkingSetSize;
	uint64_t	PeakWorkingSetSize;
	uint32_t	HardFaultCount;
	uint16_t	PartitionId;
	uint16_t	Pad0;
	struct <unnamed-tag>	u1;
	uint64_t	Reserved0;
	struct _MMSUPPORT_FLAGS	Flags;
}__attribute__((packed));
