
struct _PF_KERNEL_GLOBALS {
	uint64_t	AccessBufferAgeThreshold;
	struct _EX_RUNDOWN_REF	AccessBufferRef;
	struct _KEVENT	AccessBufferExistsEvent;
	uint32_t	AccessBufferMax;
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	uint8_t	__padding4__;
	uint8_t	__padding5__;
	uint8_t	__padding6__;
	uint8_t	__padding7__;
	uint8_t	__padding8__;
	uint8_t	__padding9__;
	uint8_t	__padding10__;
	uint8_t	__padding11__;
	uint8_t	__padding12__;
	uint8_t	__padding13__;
	uint8_t	__padding14__;
	uint8_t	__padding15__;
	uint8_t	__padding16__;
	uint8_t	__padding17__;
	uint8_t	__padding18__;
	uint8_t	__padding19__;
	struct _SLIST_HEADER	AccessBufferList;
	int32_t	StreamSequenceNumber;
	uint32_t	Flags;
	int32_t	ScenarioPrefetchCount;
}__attribute__((packed));
