
struct SYSTEM_POWER_CAPABILITIES {
	uint8_t	PowerButtonPresent;
	uint8_t	SleepButtonPresent;
	uint8_t	LidPresent;
	uint8_t	SystemS1;
	uint8_t	SystemS2;
	uint8_t	SystemS3;
	uint8_t	SystemS4;
	uint8_t	SystemS5;
	uint8_t	HiberFilePresent;
	uint8_t	FullWake;
	uint8_t	VideoDimPresent;
	uint8_t	ApmPresent;
	uint8_t	UpsPresent;
	uint8_t	ThermalControl;
	uint8_t	ProcessorThrottle;
	uint8_t	ProcessorMinThrottle;
	uint8_t	ProcessorMaxThrottle;
	uint8_t	FastSystemS4;
	uint8_t	Hiberboot;
	uint8_t	WakeAlarmPresent;
	uint8_t	AoAc;
	uint8_t	DiskSpinDown;
	uint8_t	HiberFileType;
	uint8_t	AoAcConnectivitySupported;
	uint8_t	spare3[6];
	uint8_t	__padding0__;
	uint8_t	__padding1__;
	uint8_t	__padding2__;
	uint8_t	__padding3__;
	uint8_t	__padding4__;
	uint8_t	SystemBatteriesPresent;
	uint8_t	BatteriesAreShortTerm;
	struct BATTERY_REPORTING_SCALE	BatteryScale[3];
	struct _SYSTEM_POWER_STATE	AcOnLineWake;
	struct _SYSTEM_POWER_STATE	SoftLidWake;
	struct _SYSTEM_POWER_STATE	RtcWake;
	struct _SYSTEM_POWER_STATE	MinDeviceWakeState;
	struct _SYSTEM_POWER_STATE	DefaultLowLatencyWake;
}__attribute__((packed));
